name: reviewdog
on: [pull_request]

jobs:
  analysis:
    name: complexity analysis
    runs-on: ubuntu-latest
    steps:
      - name: golang set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: checkout
        uses: actions/checkout@v2
      - name: install complexity
        run: go get github.com/shoooooman/go-complexity-analysis/cmd/complexity
      - name: reviewdog set up
        run: |
          INSTALL_SHELL=https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh
          mkdir -p $HOME/bin && curl -sfL $INSTALL_SHELL| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
          echo ::add-path::$(go env GOPATH)/bin # for Go projects
      - name: calc complexities with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -level=info
